### ISSUE TITLE
Twitter Image Notifications Show Link Rather Than Image

### ISSUE THREAD

**Issue by kaeden1100** [Re-Ignited-Development/Re-Ignited-Phone#91]
![image](https://user-images.githubusercontent.com/74526159/102852871-1044bc80-43d4-11eb-9204-26ba8e1e820f.png)

When sending a tweet as a picture through Twitter, it displays the link to the image rather than the image itself. I just updated to the latest version of GCPhone-Reignited today, and am running Screenshot-Basic with Image-Server.

Any ideas here?

**Comment by XiosBombay** [comment]
I'm pretty sure that's what's supposed to happen. Though I would wait for ROCKO for a confirmation.

**Comment by TasoOneAsia** [comment]
Hm thought I fixed with b379de95de9417148ba77a36a5cca81a04901d8f. Maybe not, would need to double check but this was working when I had tested it.

**Comment by kaeden1100** [comment]
> Hm thought I fixed with [b379de9](https://github.com/Re-Ignited-Development/Re-Ignited-Phone/commit/b379de95de9417148ba77a36a5cca81a04901d8f). Maybe not, would need to double check but this was working when I had tested it.

For what it’s worth, when I updated, I moved my confit in html/static/configs back to the new build. I wouldn’t have thought that would’ve overwritten any updates to fix the notification thing but maybe I’m wrong?

**Comment by kaeden1100** [comment]
Also, would it matter that I’m using the regularly commented out “cb” functions in the screenshot-basic exports in client/main.lua? Using the commented out one is the only way I could get the image server to work properly with the phone.

**Comment by RockySouthpaw** [comment]
So this issue should be fixed as I tested this one in game myself same as Taso did. What ESX are you on?

**Comment by kaeden1100** [comment]
> So this issue should be fixed as I tested this one in game myself same as Taso did. What ESX are you on?
 
v1 Final

**Comment by joeng2645** [comment]
i am for sure that issue been fix cause mine working prefectly... just that i wanna change the notification display to some where else beside than top right corner but i cant seems to find the path to it
any ideals

**Comment by kaeden1100** [comment]
Okay, so I just did a fresh install of GCPhone on my development server. Still having the same issue. The ONLY thing I changed in GCPhone aside from pointing the phone to the domain for the image server is the export for screenshot-basic in "GCPhone>client>main.lua.

It's set by default to use the following: "cb(json.encode({ url = resp.url }))". I commented that out and uncommented the "cb(json.encode({ url = resp.files[1].url }))" function, which is commented out by default. Uncommenting and using this function is the only way I am able to get my phone to actually send and recieve pictures properly. Could this change be what's causing my issue with the notifications?

**Comment by kaeden1100** [comment]
The image shows up in the database like so "http://10.0.0.4:3555/23-12-2020-1768ceb17a0.jpg"

**Comment by RockySouthpaw** [comment]
If you made any sort of code modifications you should of led with thats

https://cdn.discordapp.com/attachments/782743900690841654/788452795690254366/screenshot-basic.7z

Use this.

**Comment by RockySouthpaw** [comment]
> i am for sure that issue been fix cause mine working prefectly... just that i wanna change the notification display to some where else beside than top right corner but i cant seems to find the path to it
> any ideals

You have to change it in the Twitter html stuff and then rebuild the phone.

**Comment by kaeden1100** [comment]
> > i am for sure that issue been fix cause mine working prefectly... just that i wanna change the notification display to some where else beside than top right corner but i cant seems to find the path to it
> > any ideals
> 
> You have to change it in the Twitter html stuff and then rebuild the phone.

Sorry. Didn't think it would've made a huge difference given it was still there by default, just commented out. So I need to use that version of screenshot-basic and change something in Twitter html for GCPhone then rebuild the phone?

**Comment by kaeden1100** [comment]
Okay, I'd just like to formally apologize for more or less being an idiot. I missed the part in the readme where it said the screenshot server was already preconfigured and working when I originally set this up a couple months ago. I figured we still needed to create our own image server, which is what I did, which is what led to these issues. Thanks for the help regardless. Now after using the existing image server, things seem to be working perfectly. Sorry again.
